### ISSUE TITLE
Bug: callbacks not being registered or saved correctly

### ISSUE THREAD

**Issue by malikoth** [jaredks/rumps#35]
I'm not sure if this is an issue with rumps, or just with what I'm trying to do with it.

But here's a snippet of my app:

``` python
commands = OrderedDict([
    ('Play', ('play', 'play39.png')),
    ('Pause', ('pause', 'pause14.png')),
    ('Play / Pause', ('playpause', 'play40.png')),
    ('Next track', ('next track', 'step.png')),
    ('Previous track', ('previous track', 'step1.png')),
])

def _run_osascript(command, application='Spotify'):
    return subprocess.check_output([
        'osascript', '-e',
        'if application "{0}" is running then tell application "{0}" to {1}'.format(application, command)
    ]).strip()

self.menu = [rumps.MenuItem(title, icon=os.path.join('png', action[1]), dimensions=DEFAULT_ICON_SIZE, 
    callback=lambda x: self._run_osascript(action)) for title, action in commands.iteritems()]
```

The problem is that for every command that is added to the menu, they all have the correct label from the `commands` dictionary, but they all execute the lambda that was generated for the last command added.  Thus, clicking any of them executes the applescript to tell Spotify to go the previous track.

**Comment by Lennolium** [comment]
Same problem here. Unfortunately, I did not find a solution. Maybe someone found a workaround?

**Comment by SKaplanOfficial** [comment]
This is a [late binding problem](https://stackoverflow.com/questions/3431676/creating-functions-or-lambdas-in-a-loop-or-comprehension?noredirect=1&lq=1) caused by using lambdas with list comprehensions, not a problem in rumps. By the time the lambda gets called, `action` is the last value it was set to in the list comp. To get around this, you can wrap the lambda expression with another lambda, e.g.:

```python
self.menu = [rumps.MenuItem(title, dimensions=(16, 16), callback=(lambda action: lambda _: _run_osascript(action))(action[0])) for (title, action) in commands.items()]
```

You could instead rewrite the program so that menu item titles (`item.title`) are used as indices in an action-lookup dictionary.

**Comment by malikoth** [comment]
Oh my goodness. I've been working professionally in Python for close to 10 years, and I had never come across this problem, or been at all aware that this is a thing that happens; I thought I understood lambdas well enough. Thank you @SKaplanOfficial for taking the time to explain and link to additional info so that I could educate myself. You're wonderful!

**Comment by malikoth** [comment]
Not an issue with rumps
